<?php
$this->css($this->assetModule('css/admin.css'));
$this->backbone();
?>
<div id="js-notification" class="clearfix">
    <div class="alert alert-danger">
        <p><?php _e(
                'Website still dont send any push notification to mobile apps, for setup push notification service and send push notification to users please check this tips'
            ); ?></p>
        <ol>
            <li><?php echo sprintf(
                    __('Push notification work by Firebase Cloud Messaging, for more information please check %s'),
                    '<a href="https://firebase.google.com/docs/cloud-messaging/">https://firebase.google.com/docs/cloud-messaging</a>'
                ); ?></li>
            <li><?php _e('Make sure your website mobile apps support push notification service, if not please call your app developer'); ?></li>
            <li><?php _e('Setup Firebase Cloud Messaging service on google console'); ?></li>
            <li>
                <?php echo sprintf(__('Setup config file on : %s'), Pi::path('var/config/service.notification.php')); ?>
                <ul>
                    <li><?php _e('Set server key on `fcm_server_key`'); ?></li>
                    <li><?php _e('Set topic name or token on `fcm_token` if needed'); ?></li>
                </ul>
            </li>
            <li>
                <?php _e('We have some methods for push notification'); ?>
                <ul>
                    <li><?php _e('Push to all users'); ?></li>
                    <li><?php _e('Push to list or single of user ides'); ?></li>
                    <li><?php _e('Push to list or single of device tokens'); ?></li>
                    <li><?php _e('Push to topic'); ?></li>
                </ul>
            </li>
        </ol>
    </div>
    <div class="page-header">
        <h1><?php _e('Push notification'); ?></h1>
    </div>
    <div class="clearfix">
        <div class="row">
            <div class="col-md-6">
                <div class="thumbnail">
                    <div class="caption">
                        <h3><?php _e('Push to all users'); ?></h3>
                        <div class="clearfix">
                            <p class="col-md-10"><?php _e('Here you can push notification to all users than have device token'); ?></p>
                            <p class="col-md-2">
                                <button type="button" class="btn btn-primary send-push-all"
                                        data-push-all="<?php echo $this->escape($pushUrl['all']); ?>">
                                    <?php _e('Push'); ?>
                                </button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="thumbnail">
                    <div class="caption">
                        <h3><?php _e('Push to topic'); ?></h3>
                        <div class="clearfix">
                            <p class="col-md-10"><?php _e('Here you can push notification to selected topic on FCM'); ?></p>
                            <p class="col-md-2">
                                <button type="button" class="btn btn-primary send-push-topic"
                                        data-push-topic="<?php echo $this->escape($pushUrl['topic']); ?>">
                                    <?php _e('Push'); ?>
                                </button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="thumbnail">
                    <div class="caption">
                        <h3><?php _e('Push to user id'); ?></h3>
                        <div class="clearfix">
                            <p class="col-md-10"><?php _e(
                                    'Pust list of user ides ( or single id ) here, system send notification to all available device tokens on FCM'
                                ); ?></p>
                            <p class="col-md-2">
                                <button type="button" class="btn btn-primary send-push-user"
                                        data-push-user="<?php echo $this->escape($pushUrl['user']); ?>">
                                    <?php _e('Push'); ?>
                                </button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="thumbnail">
                    <div class="caption">
                        <h3><?php _e('Push by device token'); ?></h3>
                        <div class="clearfix">
                            <p class="col-md-10"><?php _e(
                                    'Pust list of device tokens ( or device token ) here, system send notification to all available device tokens on FCM'
                                ); ?></p>
                            <p class="col-md-2">
                                <button type="button" class="btn btn-primary send-push-token"
                                        data-push-token="<?php echo $this->escape($pushUrl['token']); ?>">
                                    <?php _e('Push'); ?>
                                </button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-notification'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.send-push-all').click(this.pushAllAction);
                this.$('.send-push-user').click(this.pushUserAction);
                this.$('.send-push-token').click(this.pushTokenAction);
                this.$('.send-push-topic').click(this.pushTopicAction);
            },
            pushAllAction: function (e) {
                var p = $(e.target),
                    self = this;
                $.get($('.send-push-all').data('push-all')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        if (res.status == 1) {
                            alert('<?php _e('Push notification send successfully!'); ?>');
                        } else {
                            alert('<?php _e('Error to send push notification, please check your mobile app and setting on website and firebase'); ?>');
                        }
                    };
                });
            },
            pushUserAction: function (e) {
                var p = $(e.target),
                    self = this;
                $.get($('.send-push-user').data('push-user')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        if (res.status == 1) {
                            alert('<?php _e('Push notification send successfully!'); ?>');
                        } else {
                            alert('<?php _e('Error to send push notification, please check your mobile app and setting on website and firebase'); ?>');
                        }
                    };
                });
            },
            pushTokenAction: function (e) {
                var p = $(e.target),
                    self = this;
                $.get($('.send-push-token').data('push-token')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        if (res.status == 1) {
                            alert('<?php _e('Push notification send successfully!'); ?>');
                        } else {
                            alert('<?php _e('Error to send push notification, please check your mobile app and setting on website and firebase'); ?>');
                        }
                    };
                });
            },
            pushTopicAction: function (e) {
                var p = $(e.target),
                    self = this;
                $.get($('.send-push-topic').data('push-topic')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        if (res.status == 1) {
                            alert('<?php _e('Push notification send successfully!'); ?>');
                        } else {
                            alert('<?php _e('Error to send push notification, please check your mobile app and setting on website and firebase'); ?>');
                        }
                    };
                });
            },
        }
        page.init();
    })(jQuery)
</script>