<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <?php if (isset($list) && !empty($list)) { ?>
        <h3><?php _e('List of send messages'); ?></h3>
        <div class="message-list">
            <?php foreach ($list as $sms) { ?>
                <div class="message-single clearfix">
                    <ul class="list-inline small text-muted">
                        <li><?php _e('To'); ?> : <?php echo $sms['user']['avatar-small']; ?> <?php echo $sms['user']['name']; ?></li>
                        <li class="message-divider">|</li>
                        <li><?php _e('Number'); ?> : <?php echo $sms['number']; ?></li>
                        <li class="message-divider">|</li>
                        <li><?php _e('Send on'); ?> : <?php echo $sms['time_create_view']; ?></li>
                        <li class="message-divider">|</li>
                        <li><?php _e('ID'); ?> : <?php echo $sms['id']; ?></li>
                    </ul>
                    <div class="message-content">
                        <?php echo $sms['content']; ?>
                    </div>
                </div>
            <?php } ?>
        </div>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger">
            <p><?php _e('Sms list is empty ! website still dont send any sms to users, for setup sms service and send sms to users please check this tips'); ?></p>
            <ol>
                <li><?php _e('Buy sms service and panel from one of sms service providers'); ?></li>
                <li><?php _e('Check your sms service active'); ?></li>
                <li><?php _e('Check website support your sms api'); ?></li>
                <li><?php _e('Check sms service config on module setting'); ?></li>
                <li><?php _e('If all of this steps is true, website send sms after some user actions like make order'); ?></li>
            </ol>
        </div>
    <?php } ?>
</div>